name: CI/CD Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  update-docker-image:
    name: Update Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login a Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Construye y sube la imagen de Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/midocker_mateo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/midocker_mateo:latest
